name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        working-directory: flutter_sample
        run: flutter pub get

      # Uncomment to check code formatting
      # - name: Verify formatting
      #   working-directory: flutter_sample
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        working-directory: flutter_sample
        run: flutter analyze

      - name: Run tests
        working-directory: flutter_sample
        run: flutter test
