name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        working-directory: flutter_sample
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   working-directory: my_project
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: my_project
        run: dart analyze

      - name: Run tests
        working-directory: my_project
        run: dart test
